### PR TITLE
Made build more resilient for newer PyQt4 versions. Fixes #58.

### LINKED ISSUE #58: Deprecated pyqtconfig fails build on ArchLinux
Hello

I don't know anything about this project or python at all, but it won't build on ArchLinux: `Linux 4.7.1-1-ARCH x86_64 GNU/Linux` or any other (probably).

From: https://bugs.archlinux.org/task/40842
`configure-ng.py is the new build system, pyqtconfig.py is a product of the old (deprecated) build system.`

This is my log:

``` plain
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.12") 
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig

...

[ 77%] SeExprEditor.sip'
sip: Unable to find file "QtGui/QtGuimod.sip"
make[2]: *** [src/SeExprEditor/CMakeFiles/expreditor.dir/build.make:62: src/SeExprEditor/sipexpreditorpart0.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: src/SeExprEditor/CMakeFiles/expreditor.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

### PR DESCRIPTION
**Pull request by mruegenberg**
This should fix #58 in a way that brings a working build on current Arch Linux (ie all library versions are relatively new) closer and at the same doesn't break on other systems.

### CODE REVIEW

File: src/ui/CMakeLists.txt [hunk 1]
```diff
@@ -28,7 +28,15 @@ endmacro()
...
-get_build_info(pyqt4-sip PYQT4_SIP)
+
+list(APPEND CMAKE_MODULE_PATH "/usr/share/apps/cmake/modules/") # needed for e.g Arch Linux as new versions of CMake only search a version-specific module path. Should be no problem if the path does not exist.
+find_package(PyQt4)
+set(PYQT4_SIP ${PYQT4_SIP_DIR})
+if(PYQT4_FOUND)
+
+else()
+  get_build_info(pyqt4-sip PYQT4_SIP)
+endif()
```
Comment (davvid) [inline src/ui/CMakeLists.txt]: please follow the style used in the this file ~ use 4-space indents.

File: src/ui/CMakeLists.txt [hunk 2]
```diff
@@ -28,7 +28,15 @@ endmacro()
 get_build_info(python-site PYTHON_SITE)
 get_build_info(python-inc PYTHON_INCLUDE_DIR)
 get_build_info(sip-inc SIP_INCLUDE_DIR)
-get_build_info(pyqt4-sip PYQT4_SIP)
+
+list(APPEND CMAKE_MODULE_PATH "/usr/share/apps/cmake/modules/") # needed for e.g Arch Linux as new versions of CMake only search a version-specific module path. Should be no problem if the path does not exist.
```
Comment (davvid) [inline src/ui/CMakeLists.txt]: The trailing slash (`/`) is not needed.

File: src/ui/CMakeLists.txt [hunk 3]
```diff
@@ -28,7 +28,15 @@ endmacro()
...
+find_package(PyQt4)
+set(PYQT4_SIP ${PYQT4_SIP_DIR})
+if(PYQT4_FOUND)
```
Comment (davvid) [inline src/ui/CMakeLists.txt]: It might be clearer to write this as `if (NOT PYQT4_FOUND)`. so we can avoid the empty `if ()` block.

File: src/ui/CMakeLists.txt (hunk 2 above)
Comment (davvid) [inline src/ui/CMakeLists.txt]: Please keep this comment on a separate line and wrap the comments.  The rest of this file is near 80 columns as its limit, so try to stick near that limit within reason.

While it "should be no problem" if the path does not exist, we can avoid having to guess while being a little more tidy by just checking up front.

```cmake
if (EXISTS "/usr/share/apps/cmake/modules")
    # Arch Linux ...
    list(APPEND ...)
endif()
```

**Comment by mruegenberg** [comment]
Thanks for the fast review, I've incorporated the changes you requested.
