### ISSUE TITLE
Deprecated pyqtconfig fails build on ArchLinux

### ISSUE THREAD

**Issue by MarcinWieczorek** [wdas/SeExpr#58]
Hello

I don't know anything about this project or python at all, but it won't build on ArchLinux: `Linux 4.7.1-1-ARCH x86_64 GNU/Linux` or any other (probably).

From: https://bugs.archlinux.org/task/40842
`configure-ng.py is the new build system, pyqtconfig.py is a product of the old (deprecated) build system.`

This is my log:

``` plain
-- Found PythonInterp: /usr/bin/python2.7 (found version "2.7.12") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.12") 
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig
Traceback (most recent call last):
  File "/build/seexpr/src/SeExpr-2.11/src/build/build-info", line 14, in <module>
    from PyQt4 import pyqtconfig
ImportError: cannot import name pyqtconfig

...

[ 77%] SeExprEditor.sip'
sip: Unable to find file "QtGui/QtGuimod.sip"
make[2]: *** [src/SeExprEditor/CMakeFiles/expreditor.dir/build.make:62: src/SeExprEditor/sipexpreditorpart0.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:219: src/SeExprEditor/CMakeFiles/expreditor.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

**Comment by jberlin** [comment]
Hi. Our internal build uses Linux 3.10.0 x86_64, which still has pyqtconfig.py. We haven't ported to later Linux build systems yet.

**Comment by MarcinWieczorek** [comment]
Will you?

**Comment by jberlin** [comment]
This would be a great exercise for a contributor! Otherwise, it may be a while given some of the other priorities on our plate right now.

**Comment by mruegenberg** [comment]
I've looked into this a bit and it seems that CMake provides `FindPyQt4.cmake`, which has a `PYQT4_SIP_DIR` variable. 

Replacing `get_build_info(pyqt4-sip PYQT4_SIP)` with

    find_package(PyQt4)
    set(PYQT4_SIP ${PYQT4_SIP_DIR})

should do the right thing.
(The `pyqtconfg` and `pyqt4_sip` function can then be removed from `build-info`).

**Comment by mruegenberg** [comment]
Probably not an Arch Linux-specific problem, but I had problems when linking because apparently `SeExpr2Editor` is not linked with the main `SeExpr2` lib? 
=> had to add `target_link_libraries(SeExpr2Editor ${SEEXPR_LIBRARIES})` in `ui/CMakeLists.txt`

**Comment by davvid** [comment]
Thanks for the heads-up.  As the author of the `build-info` script, I would very much like to minimize the use of it.  I doing some maintenance on the cmake setup so in my fork ( pull request #67 ) and I think I can try tackling this as a follow-up to that work.

We likely have not noticed because we use RHEL7 at work and I use Debian/testing at home, and both of those distros must still be using the old configure script since they all have `PyQt4.qtpyconfig` available.

We originally went down the `build-info` path because cmake's built-in support for finding python was buggy when using a non-system (custom) python build, and the pyqt4 stuff may have been buggy too at the time (RHEL6).  I'll have to verify that again.

Worst case scenario is we'll add a knob so that we can specify the `PYQT4_SIP_DIR` explicitly, but my goal is to make it work by default without user intervention.

RE: the `-Wno-date-time` thing -- in my pull request  removed the use of the `__DATE__` and `__TIME__` macros.  I care about reproducible builds so I took the advice suggested by the warnings.
